#define CHORDAL_HOLD
#undef TAPPING_TERM
#define TAPPING_TERM 250

#define PERMISSIVE_HOLD

#define COMBO_TERM 70

#define USB_SUSPEND_WAKEUP_DELAY 0
#define NO_AUTO_SHIFT_ALPHA
#define CAPS_LOCK_STATUS
#define SERIAL_NUMBER "e5rwR/bvgJ6x"
#define LAYER_STATE_8BIT
#define COMBO_COUNT 3

#define TAPPING_TERM_PER_KEY
#define RGB_MATRIX_STARTUP_SPD 60

#undef ENABLE_RGB_MATRIX_HUE_BREATHING
